services:
  pumba:
    image: gaiaadm/pumba
    container_name: pumba
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: netem --duration 5m rate --rate 1mbit sender
    depends_on:
      - sender

  sender:
    build:
      dockerfile: sender/Dockerfile
    container_name: sender
    environment:
      - SERVER_ADDR=receiver:1234
      - MSG_SIZE_BYTES=1000000
      - RUNS=100
    depends_on:
      - receiver

  receiver:
    build:
      dockerfile: receiver/Dockerfile
    container_name: receiver
    environment:
      - SERVER_ADDR=0.0.0.0:1234
      - MSG_SIZE_BYTES=1000000
      - RUNS=100
